//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminární_práce___soundtrack_list.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seminární_práce___soundtrack_list.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------------------------------------.
        /// </summary>
        internal static string Aijna {
            get {
                return ResourceManager.GetString("Aijna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bez_názvu {
            get {
                object obj = ResourceManager.GetObject("Bez_názvu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the select item, you can find individual sheets and delete the entire sheet.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybí seznam.
        /// </summary>
        internal static string Chyba_vkladani_seznamu {
            get {
                return ResourceManager.GetString("Chyba_vkladani_seznamu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In GB components, you can play a track, see the current sheet and play time.
        /// </summary>
        internal static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DOWN {
            get {
                object obj = ResourceManager.GetObject("DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting Error.
        /// </summary>
        internal static string Error_Insert {
            get {
                return ResourceManager.GetString("Error_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the file you can find Import and Export to a XML file.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the Help section, you will find a tutorial, program info and author info.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index value.
        /// </summary>
        internal static string Invalid_range {
            get {
                return ResourceManager.GetString("Invalid_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V GB komponenty máte možnost spustit track, vidíte aktuální list a dobu.
        /// </summary>
        internal static string Komponenty {
            get {
                return ResourceManager.GetString("Komponenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není kam posouvat.
        /// </summary>
        internal static string Mimo_rozsah {
            get {
                return ResourceManager.GetString("Mimo_rozsah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Není vybrán žádný seznam !.
        /// </summary>
        internal static string Missing_seznam {
            get {
                return ResourceManager.GetString("Missing_seznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V položce nápověda naleznete tutorial, info o programu a autorovi.
        /// </summary>
        internal static string Napoveda {
            get {
                return ResourceManager.GetString("Napoveda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatná hodnota indexu.
        /// </summary>
        internal static string Neplatny_rozsah {
            get {
                return ResourceManager.GetString("Neplatny_rozsah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowhere to slide.
        /// </summary>
        internal static string Out_of_range {
            get {
                return ResourceManager.GetString("Out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PB {
            get {
                object obj = ResourceManager.GetObject("PB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the GB song you will see the individual songs and you can add them to the track.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V GB songy uvidíte jednotlivé písničky a můžete je přidat do tracku.
        /// </summary>
        internal static string Songy {
            get {
                return ResourceManager.GetString("Songy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V položce soubor naleznete Import a Export do XML souboru.
        /// </summary>
        internal static string Soubor {
            get {
                return ResourceManager.GetString("Soubor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the GB soundtrack you will see the current soundtrack that you can change.
        /// </summary>
        internal static string Soundtracks {
            get {
                return ResourceManager.GetString("Soundtracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V GB soundtracky uvidíte aktuální soundtrack který můžete měnit.
        /// </summary>
        internal static string Soundtracky {
            get {
                return ResourceManager.GetString("Soundtracky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrán seznam: .
        /// </summary>
        internal static string The_Chosen_One {
            get {
                return ResourceManager.GetString("The_Chosen_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen list:.
        /// </summary>
        internal static string The_Chosen_One_eng {
            get {
                return ResourceManager.GetString("The_Chosen_One_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UP {
            get {
                object obj = ResourceManager.GetObject("UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte pomocí lišty nějaký seznam.
        /// </summary>
        internal static string Vyberte_seznam {
            get {
                return ResourceManager.GetString("Vyberte_seznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V položce vybrat naleznete jednotlivé listy a možnost smazat celý list.
        /// </summary>
        internal static string Vybrat {
            get {
                return ResourceManager.GetString("Vybrat", resourceCulture);
            }
        }
    }
}
